person:
  name: shy${random.uuid}}
  age: ${random.int}
  happy: false
  birth: 1996/07/30
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - sing
    - girl
  dog:
    name: ${person.hello:hello}_旺财
    age: 3
server:
  port: 8080
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false # 关闭模板引擎缓存！
  messages:
    basename: i18n.login

# debug: true 表示开启哪些自动配置生效，哪些没有生效！
# debug: true
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
